version: "3"
# https://docs.docker.com/compose/compose-file/compose-versioning/

services:
  # Ref: https://github.com/kassambara/wordpress-docker-compose/blob/master/docker-compose.yml

  # WP Dev Container [build]
  wordpress:
    depends_on:
      - mariadb

    build:
      context: ./wp
      dockerfile: dockerfile
      args:
        USER_NAME: $DB_USER
        USER_ID: $DB_USER_UID
        GROUP_ID: $DB_USER_GID
        USER_PATH: $DB_USER_PATH

    #    command: sh -c "composer install"

    image: wp_dev:2.0.0
    container_name: wp-dev

    user: "1000:1000"

    restart: unless-stopped

    ports:
      - "80:80"

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASS
      WORDPRESS_TABLE_PREFIX: $WP_DB_PREFIX
      WORDPRESS_DEBUG: 1

      WORDPRESS_CONFIG_EXTRA: |
        if(!defined('WP_DEBUG_LOG')) {
          define('WP_DEBUG_LOG', true);
        }
    volumes:
      - /var/git/repo/eny-register:/var/www/html/wp-content/plugins/eny-register
      - /var/git/repo/wp-graphql:/var/www/html/wp-content/plugins/wp-graphql
      # - /var/git/repo/eny-events-schema:/var/www/html/wp-content/plugins/eny-events-schema
      - /var/git/repo/cabov2:/var/www/html/wp-content/reactpress/apps/cabov2
      - ./wp/composer.json:/var/www/html/composer.json
      - ./wordpress:/var/www/html

    networks:
      - network-dev

  mariadb:
    build:
      context: ./db
      dockerfile: dockerfile
      args:
        USER_NAME: $DB_USER
        USER_ID: $DB_USER_UID
        GROUP_ID: $DB_USER_GID
        USER_PATH: $DB_USER_PATH

    image: db-dev:2.0.0
    container_name: db-dev

    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS

    volumes:
      - ./mysql:/var/lib/mysql

    networks:
      - network-dev

  wpcli:
    build:
      context: ./wpcli
      dockerfile: dockerfile
      args:
        USER_NAME: $DB_USER
        USER_ID: $DB_USER_UID
        GROUP_ID: $DB_USER_GID
        USER_PATH: $DB_USER_PATH

    image: wpcli-dev:2.0.0
    container_name: wpcli_dev

    user: "1000:1000"

    volumes_from:
      - wordpress

    links:
      - mariadb

    working_dir: /var/www/html

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASS

    entrypoint: wp

    command: "--info"

    networks:
      - network-dev

  adminer:
    depends_on:
      - mariadb

    image: adminer:latest
    container_name: adminer_dev

    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

    restart: unless-stopped
    ports:
      - "8080:8080"

    networks:
      - network-dev

networks:
  network-dev:
