version: "3"
 
services:
  db:
    image: mysql:8.0
    container_name: wp-dev-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    ports:
      - 42333:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      app-network:
        ipv4_address" 10.1.0.2
 
  wp:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    image: wp_dev:1.0
    container_name: wp_dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
      # Find this in WSL prompt via ifconfig
      XDEBUG_CONFIG: client_host=10.1.0.3
    volumes:
      - ./../src/plugins:/var/www/html/wp-content/plugins
      - ./../src/themes:/var/www/html/wp-content/themes
      - wpdata:/var/www/html
    networks:
      app-network:
        ipv4_address" 10.1.0.3
 
volumes:
  wpdata:
  dbdata:
 
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24