version: "3"
# https://docs.docker.com/compose/compose-file/compose-versioning/

services:
  # Ref: https://github.com/kassambara/wordpress-docker-compose/blob/master/docker-compose.yml

  # WP Dev Container [build]
  wordpress:
    depends_on:
      - mariadb
    
    build:
      context: ./wp
      dockerfile: dockerfile
    
    command: sh -c "composer install"
    
    image: wp_dev:2.0.0
    container_name: wp-dev

    user: "1000:1000"

    restart: unless-stopped

    ports:
      - "80:80"

    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASS
      WORDPRESS_TABLE_PREFIX: $WP_DB_PREFIX
      WORDPRESS_DEBUG: 1

    volumes:
      - /var/lib/git/repo/eny_events:/var/www/html/wp-content/plugins/eny-events
      - /var/lib/git/eny/eny_querystr/eny-invited:/var/www/html/wp-content/plugins/eny-invited
      - /var/lib/git/eny/nmi-elite:/var/www/html/wp-content/plugins/eny-ppb
      - ./wordpress:/var/www/html

  mariadb:
    build:
      context: ./db
      dockerfile: dockerfile

    image: db-dev:1.0.0
    container_name: db-dev

    restart: unless-stopped

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS 
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS

    volumes:
      - ./mysql:/var/lib/mysql

  wpcli:
    build:
      context: ./wpcli
      dockerfile: dockerfile
    container_name: wpcli_dev
    
    user: "1000:1000"

    volumes:
      - ./wordpress:/var/www/html
    
    working_dir: /var/www/html
    
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASS

  adminer:
    depends_on:
      - mariadb

    image: adminer:latest
    container_name: adminer

    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

    restart: unless-stopped
    ports:
      - "8080:8080"
  
  healthcheck:
    image: wpcli
    build: ./wpcli/
    container_name: healthcheck_dev
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=mariadb:3306, wordpress:80