# https://hub.docker.com/_/wordpress/
FROM wordpress:latest

USER root

RUN apt-get -y update && apt-get upgrade 
RUN apt-get install -y curl make zip unzip dnsutils
# RUN apt-get install -y php-curl php-xml php-zip php-mbstring 
# RUN apt-get install -y composer

RUN apt-get clean -y

# XDebug (thinking abouty using apt-get over pecl)
RUN pecl install xdebug 
RUN docker-php-ext-enable xdebug
RUN apt-get -y update && apt-get upgrade 

# Composer Install (https://getcomposer.org/doc/00-intro.md#locally)
#COPY --from=composer/composer /usr/bin/composer /usr/bin/composer
#RUN composer self-update
#RUN apt-get install -y composer

# Add global composer dir to path (installed phpunit from global)
# should make this more universal by getting this path via composer and then adding it
#ENV PATH="${PATH}:/home/geoff/.composer/vendor/bin"

# Install PHP Unit
#RUN composer global require --dev phpunit/phpunit:9.*

RUN useradd -ms /bin/bash -u 1000 geoff
RUN usermod -a -G root geoff
RUN chmod -R g+rw /var/www/html/wp-content