FROM wordpress:cli

# SUDO
USER root

RUN apk update
RUN apk add --no-cache bash
RUN apk add --no-cache shadow

RUN chmod 0640 /etc/shadow

RUN useradd -ms /bin/bash -u 1000 -G www-data gedefili
RUN usermod -a -G root gedefili